name: Build and Test

on:
  pull_request:
  push:
    branches:
      - dev-piedone

jobs:
  build-and-test:
    name: Build and Test
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      timeout-minutes: 5
    permissions:
      actions: write
      contents: read

  codespell:
    name: Codespell
    uses: Lombiq/GitHub-Actions/.github/workflows/codespell.yml@dev
    permissions:
      actions: write
      contents: read
